name: tap-nhl-cicd
on:
  workflow_dispatch:
  pull_request:
    branchs:
      - 'main'

jobs:
  tap-nhl-cicd:
    name: tap-nhl-cicd
    runs-on: ubuntu-latest
    env:
      python-version: 3.8.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install meltano==1.96.0
          meltano install
      - name: Dynamically set environment variables
        run: |
          echo "START_YEAR=2020" >> $GITHUB_ENV
          echo "END_YEAR=2021" >> $GITHUB_ENV
      - name: Run tap-nhl to target-jsonl
        run: |
          meltano --environment=cicd elt tap-nhl target-jsonl
